name:               "Luka Lickah"
description:        "Desenvolvedor junior, múscio e cervejeiro"

url:                ""
author:             "Luka Lickah"
email:              "lukamatheus0@gmail.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            "lickahluka"
email:              "ukamatheus0@gmail.com@"
github:             "sommen01"
linkedin:           "luka-lickah-972775190"

disqus_shortname:   "thinker3197"

background:         "https://web.whatsapp.com/pp?e=https%3A%2F%2Fpps.whatsapp.net%2Fv%2Ft61.24694-24%2F75236152_435290947141996_182007710935745937_n.jpg%3Foe%3D5E14F420%26oh%3Db791b5656133227a6db7eb8277098b19&t=l&u=556796228209%40c.us&i=1576066233"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "Sobre"
    href:           "/sobre"
  

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate