name:               "Luka Lickah"
description:        "Desenvolvedor júnior"

url:                "http://lukalickah.dev"
author:             "Luka Lickah"
email:              "lukamatheus0@gmail.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            "lickahluka"
email:              "ukamatheus0@gmail.com@"
github:             "sommen01"
linkedin:           "luka-lickah-972775190"

disqus_shortname:   ""

background:         "https://66.media.tumblr.com/59994b33ccbe03f9dc0be1c3ca24072f/tumblr_piznhiQ31F1ql9a3vo2_500.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "Sobre"
    href:           "/sobre"
  

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate