name:               "Luka Lickah"
description:        "Desenvolvedor junior"

url:                "http://www.dl-digital.com/images/Astronomy/Nebulae/Rosette-Bok-64-Frame-Halpa-crop-v4preHDcropNew2.jpg"
author:             "Luka Lickah"
email:              "lukamatheus0@gmail.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            "lickahluka"
email:              "ukamatheus0@gmail.com@"
github:             "sommen01"
linkedin:           "luka-lickah-972775190"

disqus_shortname:   "thinker3197"

background:         "http://www.dl-digital.com/images/Astronomy/Nebulae/Rosette-Bok-64-Frame-Halpa-crop-v4preHDcropNew2.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "Sobre"
    href:           "/sobre"
  

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate